apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-test
  labels:
    app: configmap-test
data:
  config.json: |
    {
      "config": {
        "message": "v1" 
      }
    }
---
kind: Service
apiVersion: v1
metadata:
  name: configmap-test
spec:
  selector:
    app: configmap-test
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-test
spec:
  selector:
    matchLabels:
      app: configmap-test
  template:
    metadata:
      labels:
        app: configmap-test
    spec:
      containers:
        - name: configmap-test
          image: expcat/configmap-test:1.2
          env: 
            - name: DOTNET_USE_POLLING_FILE_WATCHER
              value: "true"
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /src/conf
      volumes:
        - name: config
          configMap:
            name: configmap-test
