apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapreload-test
  labels:
    app: configmapreload-test
data:
  config.json: |
    {
      "config": {
        "message": "v1" 
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmapreload-test
spec:
  selector:
    matchLabels:
      app: configmapreload-test
  template:
    metadata:
      labels:
        app: configmapreload-test
    spec:
      containers:
        - name: configmapreload-test
          image: configmapreloadtest:1.0.0
          env: 
            - name: DOTNET_USE_POLLING_FILE_WATCHER
              value: "true"
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /app/conf
      volumes:
        - name: config
          configMap:
            name: configmapreload-test
